-- Create public.users table (extends auth.users)
create table public.users (
  id uuid references auth.users not null primary key,
  first_name text,
  last_name text,
  email text,
  date_of_birth date,
  role text default 'user',
  plan text default 'free',
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.users enable row level security;

-- Trigger to create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, email, first_name, last_name, date_of_birth)
  values (
    new.id, 
    new.email, 
    new.raw_user_meta_data->>'first_name', 
    new.raw_user_meta_data->>'last_name',
    (new.raw_user_meta_data->>'date_of_birth')::date
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Stories Table
create table public.stories (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) not null,
  title text not null,
  genre text not null,
  language text default 'English',
  goal text,
  lesson text,
  is_completed boolean default false,
  is_published boolean default false,
  full_story text,
  likes integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.stories enable row level security;

-- Story Parts Table
create table public.story_parts (
  id bigint generated by default as identity primary key,
  story_id bigint references public.stories(id) on delete cascade not null,
  part_number integer not null,
  content text not null,
  is_user_input boolean default false,
  generated_img text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.story_parts enable row level security;

-- Job Queue Table (for Edge Functions)
create table public.jobs (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.users(id) not null,
  type text not null, -- 'generate_start', 'continue_story', etc.
  status text default 'pending', -- 'pending', 'processing', 'completed', 'failed'
  params jsonb, -- { genre: 'adventure', ... }
  result jsonb, -- { story_id: 123, ... }
  error text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.jobs enable row level security;

-- Contact Messages
create table public.contact_messages (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  subject text,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.contact_messages enable row level security;

-- RLS Policies (Simplified)
create policy "Users can view own profile" on public.users for select using (auth.uid() = id);
create policy "Users can update own profile" on public.users for update using (auth.uid() = id);

create policy "Users can view own stories" on public.stories for select using (auth.uid() = user_id);
create policy "Users can insert own stories" on public.stories for insert with check (auth.uid() = user_id);
create policy "Users can update own stories" on public.stories for update using (auth.uid() = user_id);
create policy "Users can delete own stories" on public.stories for delete using (auth.uid() = user_id);
create policy "Anyone can view published stories" on public.stories for select using (is_published = true);

create policy "Users can view parts of own stories" on public.story_parts for select using (exists (select 1 from public.stories where id = story_parts.story_id and user_id = auth.uid()));
create policy "Users can insert parts" on public.story_parts for insert with check (exists (select 1 from public.stories where id = story_parts.story_id and user_id = auth.uid()));

create policy "Users can view own jobs" on public.jobs for select using (auth.uid() = user_id);
create policy "Users can insert own jobs" on public.jobs for insert with check (auth.uid() = user_id);
